project:
  type: book

book:
  title: "CSHL Computational Genomics 2022"
  description: Course material (lectures and workshops) from Stephanie Hicks
  author: "Stephanie Hicks"
  date: "2022-11-29"
  chapters:
    - index.qmd
    - intro-to-r.qmd
    - exercises-01.qmd
    - reproducible-res.qmd
    - exercises-02.qmd
    - tidyverse.qmd
    - exercises-03.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

execute:
  freeze: auto

